[package]
name = "graf_zahl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.20"
quicli = "0.4.0"
structopt = "0.3.26"
colored = "2.1.0"
regex = "1.9.6"
